# Generated by Django 5.0.6 on 2024-06-02 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_course_price_lesson_price"),
        ("users", "0004_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="SendPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_date", models.DateField(auto_now_add=True, verbose_name="дата платежа")),
                (
                    "session_id",
                    models.CharField(
                        blank=True, help_text="Введите Id сессии", max_length=255, null=True, verbose_name="Id сессии"
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Укажите ссылку",
                        max_length=400,
                        null=True,
                        verbose_name="Ссылка на оплату",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lms.course",
                        verbose_name="оплачиваемый курс",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lms.lesson",
                        verbose_name="оплачиваемый урок",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="плательщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "оплата услуг",
                "verbose_name_plural": "оплата услуг",
            },
        ),
    ]
