# Generated by Django 5.0.6 on 2024-06-09 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_course_price_lesson_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="up_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата обновления"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="up_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата обновления"),
        ),
    ]
